// Pure code generator for the inbox-watcher Apps Script that
// `deploy_inbox_watcher` ships. No I/O — it returns the two file SOURCES
// (Code.gs + the appsscript.json manifest) as strings; the tool layer writes
// them through the AppsScriptClient.
//
// THE TRIGGER LIMITATION (load-bearing): the Apps Script REST API cannot
// create time-based triggers. Only `ScriptApp.newTrigger(...)` running INSIDE
// the project can. So the generated script ships an `installTrigger()` function
// the user runs ONCE by hand; that single manual run arms the time-trigger,
// after which the poll function fires on its own. The tool returns this exact
// next step. We never claim the deploy alone makes the watcher live.

/** Apps Script `everyMinutes` only accepts this set; we clamp to the nearest. */
const ALLOWED_MINUTES = [1, 5, 10, 15, 30] as const;

export type WatcherScriptOpts = {
  /** Gmail search the poll runs (e.g. `is:unread in:inbox`). */
  query: string;
  /** Task list id the new tasks land in (`@default` is the user's main list). */
  tasklist: string;
  /** Name of the polling function (also the trigger handler). */
  pollFunction: string;
  /** Name of the one-time trigger-install function. */
  installFunction: string;
  /** Desired poll cadence; clamped to {1,5,10,15,30}. */
  everyMinutes: number;
  /** Max threads processed per poll (Gmail search page size). */
  maxThreads: number;
};

export type WatcherScriptFiles = {
  /** `Code.gs` source (Apps Script file type `SERVER_JS`). */
  code: string;
  /** `appsscript.json` manifest source (file type `JSON`). */
  manifest: string;
  /** The cadence actually used after clamping. */
  everyMinutes: number;
};

/** Clamp an arbitrary minute cadence to the nearest Apps Script-allowed value. */
export function clampEveryMinutes(minutes: number): number {
  let best = ALLOWED_MINUTES[0] as number;
  let bestDelta = Math.abs(minutes - best);
  for (const m of ALLOWED_MINUTES) {
    const d = Math.abs(minutes - m);
    if (d < bestDelta) {
      best = m;
      bestDelta = d;
    }
  }
  return best;
}

/** JSON-encode a string for safe embedding inside generated JS source. */
function js(value: string): string {
  return JSON.stringify(value);
}

export function buildWatcherScript(opts: WatcherScriptOpts): WatcherScriptFiles {
  const everyMinutes = clampEveryMinutes(opts.everyMinutes);
  const maxThreads = Math.max(1, Math.min(100, Math.floor(opts.maxThreads)));

  const code = `// Auto-generated by flow-smart deploy_inbox_watcher.
// Polls Gmail and files unread threads as Google Tasks. The time trigger is
// NOT created by the deploy (the Apps Script API cannot create triggers) —
// run ${opts.installFunction}() ONCE in the editor to arm it.

var WATCHER_QUERY = ${js(opts.query)};
var WATCHER_TASKLIST = ${js(opts.tasklist)};
var WATCHER_MAX_THREADS = ${maxThreads};

/**
 * Poll the inbox and create one Task per matching unread thread, then mark the
 * thread read so it is not re-filed on the next poll. Idempotent across runs
 * via the read-marking. Wired as the time-trigger handler by ${opts.installFunction}.
 */
function ${opts.pollFunction}() {
  var threads = GmailApp.search(WATCHER_QUERY, 0, WATCHER_MAX_THREADS);
  for (var i = 0; i < threads.length; i++) {
    var thread = threads[i];
    var messages = thread.getMessages();
    if (!messages.length) continue;
    var msg = messages[messages.length - 1];
    var title = msg.getSubject() || '(no subject)';
    var notes = msg.getPlainBody().slice(0, 500) +
      '\\n\\nFrom Gmail thread ' + thread.getId();
    Tasks.Tasks.insert({ title: title, notes: notes }, WATCHER_TASKLIST);
    thread.markRead();
  }
}

/**
 * ONE-TIME setup: install the time-based trigger that runs ${opts.pollFunction}
 * every ${everyMinutes} minutes. Run this MANUALLY once from the editor; the
 * REST API cannot do it. Removes any pre-existing trigger for the same handler
 * first so re-running does not stack duplicates.
 */
function ${opts.installFunction}() {
  var existing = ScriptApp.getProjectTriggers();
  for (var i = 0; i < existing.length; i++) {
    if (existing[i].getHandlerFunction() === ${js(opts.pollFunction)}) {
      ScriptApp.deleteTrigger(existing[i]);
    }
  }
  ScriptApp.newTrigger(${js(opts.pollFunction)})
    .timeBased()
    .everyMinutes(${everyMinutes})
    .create();
}
`;

  const manifest = JSON.stringify(
    {
      timeZone: "Etc/UTC",
      runtimeVersion: "V8",
      exceptionLogging: "STACKDRIVER",
      dependencies: {
        enabledAdvancedServices: [
          { userSymbol: "Tasks", serviceId: "tasks", version: "v1" },
        ],
      },
      oauthScopes: [
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/tasks",
        "https://www.googleapis.com/auth/script.scriptapp",
      ],
    },
    null,
    2,
  );

  return { code, manifest, everyMinutes };
}
